### PR TITLE
Adds the missing file back.

### PR DESCRIPTION
**Pull request by alexgorbatchev**

### CODE REVIEW

**Comment by eventualbuddha** [comment]
When did these files go missing?

**Comment by alexgorbatchev** [comment]
@iamJoeTaylor did you force push master? I didn't have 357640d in my PR earlier...

@eventualbuddha dunno, didn't check... fresh install failed, so i had to fix it :)

**Comment by eventualbuddha** [comment]
I don't understand. The `master` branch is currently 54421906977e871a8d14ee9544ca567e238ccc12, which includes both [lib/input-sim.js](https://github.com/iamJoeTaylor/input-sim/blob/54421906977e871a8d14ee9544ca567e238ccc12/lib/input-sim.js) and [src/input-sim.js](https://github.com/iamJoeTaylor/input-sim/blob/54421906977e871a8d14ee9544ca567e238ccc12/src/input-sim.js).

**Comment by alexgorbatchev** [comment]
you know, i don't understand it either... when I cloned and pulled the repo, the master was and still is at 357640d... that's very strange, but if it's not an issue, i'm going to close this

https://github.com/alexgorbatchev/input-sim/commits/master

input-sim 2015-08-13 08-32-47

**Pull request closed without merging**
